name: Send Artifacts Workflow
env:
  REGION: us-east-1
  VERSION: ${{ secrets.VERSION }}
  RELEASE_BRANCH: main
on: 
  workflow_run:
    workflows: ["Push Workflow"]
    types: [completed]
jobs:
  notify-job:
    runs-on: ubuntu-latest
    name: Send workflow information to endpoint
    environment: notify_env
    permissions:
      id-token: write
      contents: read
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install required system packages
        run: |
          pip install --upgrade --force-reinstall -r deployment/requirements.txt 2> error.txt
          if [ -s error.txt ]; then
            echo "ERROR: System package installation failed."
            cat error.txt
            exit 1
          fi
      - name: Set up environment variables
        run: |
          export WORKFLOW_RUN_ID=${{ github.event.workflow_run.id }} 
          export COMMIT_ID=${{ github.event.workflow_run.head_sha }}
          export BRANCH=${{ github.event.workflow_run.head_branch }}
          export WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
          export NOTIFICATION_ENDPOINT=${{ secrets.ENDPOINT }}

          echo WORKFLOW_RUN_ID=$WORKFLOW_RUN_ID >> $GITHUB_ENV
          echo COMMIT_ID=$COMMIT_ID >> $GITHUB_ENV
          echo NOTIFICATION_ENDPOINT=$NOTIFICATION_ENDPOINT >> $GITHUB_ENV
          echo BRANCH=$BRANCH >> $GITHUB_ENV
          echo WORKFLOW_NAME=$WORKFLOW_NAME >> $GITHUB_ENV
      - name: Determine pipeline type
        run: |
          if [ $GITHUB_REF_NAME == $RELEASE_BRANCH ]; then
            export PIPELINE_TYPE="release"
          else
            export PIPELINE_TYPE="feature"
          fi
          echo PIPELINE_TYPE=$PIPELINE_TYPE >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.NOTIFY_ROLE }}
          aws-region: ${{ env.REGION }}
          role-duration-seconds: 900
      - name: Invoke endpoint
        run: |
          cd deployment
          python end-workflow-notification.py
